Update frontend/aws/sync/action.yml
Co-authored-by: Srdjan <91488317+srdjanflybits@users.noreply.github.com>

diff --git a/frontend/aws/sync/action.yml b/frontend/aws/sync/action.yml
--- a/frontend/aws/sync/action.yml
+++ b/frontend/aws/sync/action.yml
@@ -66,7 +66,11 @@ runs:
     - name: Invalidate CloudFront cache
       shell: bash
       run: |
-        INVALIDATION_JSON=$(aws cloudfront create-invalidation --distribution-id ${{ inputs.aws-cloudfront-distribution-id }} --paths "/*")
+                if [ $? -ne 0 ]; then
+          echo "Failed to create CloudFront invalidation"
+          exit 1
+        fi
+
         INVALIDATION_ID=$(echo $INVALIDATION_JSON | jq -r '.Invalidation.Id')
         INVALIDATION_STATUS=$(echo $INVALIDATION_JSON | jq -r '.Invalidation.Status')
 
