Change JWT authentication to bearer

diff --git a/backend/clean-docker/action.yaml b/backend/clean-docker/action.yaml
--- a/backend/clean-docker/action.yaml
+++ b/backend/clean-docker/action.yaml
@@ -57,16 +57,16 @@ runs:
           response_body=$(<response.txt)
           if [[ $http_code -ne 200 ]]; then
             echo "Request failed..."
-            break
+            exit 1
           fi
 
           TAGS=$(echo "$response_body" | jq -r '.results[] | select(.name | endswith(".dev")) | .name' | sort -r)
           if [[ -z "$TAGS" ]]; then
               echo "No Tags found."
-              break
+              exit 1
           fi
            
-          # TAGS=$(curl -s -H "Authorization: JWT $DOCKER_TOKEN" "https://hub.docker.com/v2/repositories/$REPO/tags?page=$CURRENT_PAGE&page_size=100" | jq -r '.results[] | select(.name | endswith(".dev")) | .name' | sort -r)
+          # TAGS=$(curl -s -H "Authorization: Bearer $DOCKER_TOKEN" "https://hub.docker.com/v2/repositories/$REPO/tags?page=$CURRENT_PAGE&page_size=100" | jq -r '.results[] | select(.name | endswith(".dev")) | .name' | sort -r)
 
           # Get tags to delete (skip the first N tags)
           TAGS_TO_DELETE=$(echo "$TAGS" | tail -n +$((KEEP_LATEST + 1)))
@@ -75,13 +75,13 @@ runs:
           for TAG in $TAGS_TO_DELETE; do
             echo "Deleting tag: $TAG"
 
-              response=$(curl -s -X DELETE -o response.txt -w "%{http_code}" -H "Authorization: JWT $DOCKER_TOKEN" "https://hub.docker.com/v2/repositories/$REPO/tags/$TAG")
-              http_code="${response: -3}"
-              if [[ $http_code -ne 204 ]]; then
-                response_body=$(<response.txt)
-                echo "Deleting $TAG Request failed ... $response_body"
-                break
-              fi
+            response=$(curl -s -X DELETE -o response.txt -w "%{http_code}" -H "Authorization: Bearer $DOCKER_TOKEN" "https://hub.docker.com/v2/repositories/$REPO/tags/$TAG")
+            http_code="${response: -3}"
+            if [[ $http_code -ne 204 ]]; then
+              response_body=$(<response.txt)
+              echo "Deleting $TAG Request failed $http_code ... $response_body"
+              exit 1
+            fi
           done
 
           if [[ "$next" == "null" ]]; then
